version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - "*"
    ignore:
      - dependency-name: "Microsoft.Bcl.AsyncInterfaces"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - "*"
