name: Check C# Formatting

on:
  pull_request:
    branches: [main]

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check C# Formatting
    steps:
      - uses: bmazzarol/bmazzarol/.github/actions/check-code-format@main
