name: Check Commit Message

on:
  pull_request:
    branches: [ main ]

jobs:
  commitlint:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: bmazzarol/bmazzarol/.github/actions/check-commit-message@main
