name: "Check C# Formatting"

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check C# Formatting
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Install dotnet Tooling
        run: dotnet tool restore
      - name: Check format
        run: dotnet csharpier . --check
