name: Report Coverage

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  coverage:
    name: Collect Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        project-name:
          - BunsenBurner
          - BunsenBurner.AutoFixture
          - BunsenBurner.Background
          - BunsenBurner.Bogus
          - BunsenBurner.FunctionApp
          - BunsenBurner.Hedgehog
          - BunsenBurner.Http
          - BunsenBurner.Logging
          - BunsenBurner.Verify.Xunit
          - BunsenBurner.Verify.NUnit
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Test
        run: dotnet test ${{ matrix.project-name }}.Tests/${{ matrix.project-name }}.Tests.csproj --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
      - name: Copy Coverage File
        run: cp ${{ matrix.project-name }}.Tests/TestResults/*/coverage.info ${{ matrix.project-name }}.Tests/TestResults/coverage.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ matrix.project-name }}.Tests/TestResults/coverage.info
          flag-name: ${{ matrix.project-name }}
          parallel: true
  finish:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true