name: "Sync Wiki"

on:
  push:
    branches:
      - main
    paths:
      - "Docs/**"
  repository_dispatch:
    types: [ docs ]
  gollum:

env:
  GIT_AUTHOR_NAME: Ben Mazzarol
  GIT_AUTHOR_EMAIL: bmazzarol@gmail.com

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: Docs
          destination: wiki
          token: ${{ secrets.github_token }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: main
  
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.github_token }}
          ref: main
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: Docs
          token: ${{ secrets.github_token }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: main